"""
Report Generator for Deep Research Report Generation Agent System
Implements the generation layer based on report template engine
"""
import asyncio
import logging
from typing import Dict, List, Any, Optional
from datetime import datetime
from jinja2 import Template, Environment, FileSystemLoader
import os

from config import REPORT_TEMPLATE_PATH, DEFAULT_REPORT_FORMAT

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generates structured reports from research results
    Implements the generation layer based on report template engine
    """
    
    def __init__(self):
        # Create templates directory if it doesn't exist
        os.makedirs(REPORT_TEMPLATE_PATH, exist_ok=True)
        
        # Initialize Jinja2 environment
        self.env = Environment(loader=FileSystemLoader(REPORT_TEMPLATE_PATH))
        
        # Create default templates if they don't exist
        self._create_default_templates()
        
        logger.info("Report Generator initialized with template engine")
    
    def _create_default_templates(self):
        """Create default report templates"""
        # Markdown template
        markdown_template = """# {{ title }}

**Research Query:** {{ query }}
**Generated on:** {{ timestamp }}
**Confidence Level:** {{ confidence_level }}

## Summary

{{ summary }}

## Key Findings

{% for finding in key_findings %}
- {{ finding }}
{% endfor %}

## Analysis

{{ analysis }}

{% if sources and include_sources %}
## Sources

{% for source in sources %}
1. [{{ source.title }}]({{ source.url }}) - {{ source.summary[:100] }}...
{% endfor %}
{% endif %}

{% if contradictions %}
## Contradictions Identified

{% for contradiction in contradictions %}
- {{ contradiction }}
{% endfor %}
{% endif %}

{% if gaps %}
## Information Gaps

{% for gap in gaps %}
- {{ gap }}
{% endfor %}
{% endif %}

---
*Generated by Deep Research Report Generation Agent System*
"""
        
        # Save markdown template
        template_path = os.path.join(REPORT_TEMPLATE_PATH, "markdown_report.md.j2")
        if not os.path.exists(template_path):
            with open(template_path, 'w') as f:
                f.write(markdown_template)
        
        # HTML template
        html_template = """<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #333; }
        .metadata { background-color: #f5f5f5; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .section { margin: 20px 0; }
        .source { margin: 10px 0; padding: 10px; border-left: 3px solid #ccc; }
    </style>
</head>
<body>
    <h1>{{ title }}</h1>
    
    <div class="metadata">
        <p><strong>Research Query:</strong> {{ query }}</p>
        <p><strong>Generated on:</strong> {{ timestamp }}</p>
        <p><strong>Confidence Level:</strong> {{ confidence_level }}</p>
    </div>
    
    <div class="section">
        <h2>Summary</h2>
        <p>{{ summary }}</p>
    </div>
    
    <div class="section">
        <h2>Key Findings</h2>
        <ul>
        {% for finding in key_findings %}
            <li>{{ finding }}</li>
        {% endfor %}
        </ul>
    </div>
    
    <div class="section">
        <h2>Analysis</h2>
        <p>{{ analysis }}</p>
    </div>
    
    {% if sources and include_sources %}
    <div class="section">
        <h2>Sources</h2>
        {% for source in sources %}
        <div class="source">
            <h3><a href="{{ source.url }}" target="_blank">{{ source.title }}</a></h3>
            <p>{{ source.summary[:200] }}...</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    
    {% if contradictions %}
    <div class="section">
        <h2>Contradictions Identified</h2>
        <ul>
        {% for contradiction in contradictions %}
            <li>{{ contradiction }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    
    {% if gaps %}
    <div class="section">
        <h2>Information Gaps</h2>
        <ul>
        {% for gap in gaps %}
            <li>{{ gap }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    
    <hr>
    <p><em>Generated by Deep Research Report Generation Agent System</em></p>
</body>
</html>
"""
        
        # Save HTML template
        template_path = os.path.join(REPORT_TEMPLATE_PATH, "html_report.html.j2")
        if not os.path.exists(template_path):
            with open(template_path, 'w') as f:
                f.write(html_template)
    
    async def generate_report(self, research_result: Dict[str, Any], format_type: str = "markdown", include_sources: bool = True) -> str:
        """
        Generate a report from research results
        Implements the report generation based on templates from architecture
        """
        logger.info(f"Generating {format_type} report for query: {research_result['query'][:50]}...")
        
        # Extract data from research result
        query = research_result.get("query", "Unknown Query")
        analysis = research_result.get("analysis", {})
        validated_findings = research_result.get("validated_findings", {})
        gathered_info = research_result.get("gathered_information", {})
        
        # Prepare report data
        report_data = {
            "title": f"Research Report: {query}",
            "query": query,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "summary": analysis.get("summary", "No summary available"),
            "key_findings": analysis.get("key_findings", []),
            "analysis": analysis.get("summary", "No analysis available"),
            "sources": gathered_info.get("sources", []),
            "contradictions": analysis.get("contradictions", []),
            "gaps": analysis.get("gaps", []),
            "confidence_level": validated_findings.get("confidence_level", 0.0),
            "include_sources": include_sources
        }
        
        # Generate report based on format
        if format_type.lower() == "html":
            report = await self._generate_html_report(report_data)
        elif format_type.lower() == "markdown":
            report = await self._generate_markdown_report(report_data)
        else:
            # Default to markdown
            report = await self._generate_markdown_report(report_data)
        
        logger.info(f"Report generated successfully in {format_type} format")
        return report
    
    async def _generate_markdown_report(self, report_data: Dict[str, Any]) -> str:
        """Generate a markdown report"""
        try:
            template = self.env.get_template("markdown_report.md.j2")
            return template.render(**report_data)
        except Exception as e:
            logger.error(f"Error generating markdown report: {str(e)}")
            # Fallback to simple markdown format
            return self._fallback_markdown_report(report_data)
    
    async def _generate_html_report(self, report_data: Dict[str, Any]) -> str:
        """Generate an HTML report"""
        try:
            template = self.env.get_template("html_report.html.j2")
            return template.render(**report_data)
        except Exception as e:
            logger.error(f"Error generating HTML report: {str(e)}")
            # Fallback to simple HTML format
            return self._fallback_html_report(report_data)
    
    def _fallback_markdown_report(self, report_data: Dict[str, Any]) -> str:
        """Generate a fallback markdown report if template fails"""
        report = f"# {report_data['title']}\n\n"
        report += f"**Research Query:** {report_data['query']}\n"
        report += f"**Generated on:** {report_data['timestamp']}\n"
        report += f"**Confidence Level:** {report_data['confidence_level']:.2f}\n\n"
        
        report += "## Summary\n\n"
        report += f"{report_data['summary']}\n\n"
        
        report += "## Key Findings\n\n"
        for finding in report_data['key_findings']:
            report += f"- {finding}\n"
        report += "\n"
        
        report += "## Analysis\n\n"
        report += f"{report_data['analysis']}\n\n"
        
        if report_data['sources'] and report_data['include_sources']:
            report += "## Sources\n\n"
            for i, source in enumerate(report_data['sources'], 1):
                report += f"{i}. [{source['title']}]({source['url']}) - {source['summary'][:100]}...\n"
            report += "\n"
        
        if report_data['contradictions']:
            report += "## Contradictions Identified\n\n"
            for contradiction in report_data['contradictions']:
                report += f"- {contradiction}\n"
            report += "\n"
        
        if report_data['gaps']:
            report += "## Information Gaps\n\n"
            for gap in report_data['gaps']:
                report += f"- {gap}\n"
            report += "\n"
        
        report += "---\n"
        report += "*Generated by Deep Research Report Generation Agent System*\n"
        
        return report
    
    def _fallback_html_report(self, report_data: Dict[str, Any]) -> str:
        """Generate a fallback HTML report if template fails"""
        report = "<!DOCTYPE html>\n<html>\n<head>\n"
        report += f"<title>{report_data['title']}</title>\n"
        report += "<style>body { font-family: Arial, sans-serif; margin: 40px; }</style>\n"
        report += "</head>\n<body>\n"
        
        report += f"<h1>{report_data['title']}</h1>\n"
        report += f"<p><strong>Research Query:</strong> {report_data['query']}</p>\n"
        report += f"<p><strong>Generated on:</strong> {report_data['timestamp']}</p>\n"
        report += f"<p><strong>Confidence Level:</strong> {report_data['confidence_level']:.2f}</p>\n"
        
        report += "<h2>Summary</h2>\n"
        report += f"<p>{report_data['summary']}</p>\n"
        
        report += "<h2>Key Findings</h2>\n<ul>\n"
        for finding in report_data['key_findings']:
            report += f"<li>{finding}</li>\n"
        report += "</ul>\n"
        
        report += "<h2>Analysis</h2>\n"
        report += f"<p>{report_data['analysis']}</p>\n"
        
        if report_data['sources'] and report_data['include_sources']:
            report += "<h2>Sources</h2>\n<ul>\n"
            for source in report_data['sources']:
                report += f"<li><a href='{source['url']}' target='_blank'>{source['title']}</a> - {source['summary'][:100]}...</li>\n"
            report += "</ul>\n"
        
        if report_data['contradictions']:
            report += "<h2>Contradictions Identified</h2>\n<ul>\n"
            for contradiction in report_data['contradictions']:
                report += f"<li>{contradiction}</li>\n"
            report += "</ul>\n"
        
        if report_data['gaps']:
            report += "<h2>Information Gaps</h2>\n<ul>\n"
            for gap in report_data['gaps']:
                report += f"<li>{gap}</li>\n"
            report += "</ul>\n"
        
        report += "<hr>\n"
        report += "<p><em>Generated by Deep Research Report Generation Agent System</em></p>\n"
        report += "</body>\n</html>"
        
        return report
    
    async def generate_executive_summary(self, research_result: Dict[str, Any]) -> str:
        """Generate a brief executive summary of the research"""
        query = research_result.get("query", "Unknown Query")
        analysis = research_result.get("analysis", {})
        validated_findings = research_result.get("validated_findings", {})
        
        summary_data = {
            "title": f"Executive Summary: {query}",
            "query": query,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "summary": analysis.get("summary", "No summary available")[:500],  # Truncate to first 500 chars
            "key_findings": analysis.get("key_findings", [])[:3],  # Only first 3 key findings
            "confidence_level": validated_findings.get("confidence_level", 0.0),
            "include_sources": False  # Don't include sources in executive summary
        }
        
        # Use the markdown template for executive summary
        template_content = """# {{ title }}

**Research Query:** {{ query }}
**Generated on:** {{ timestamp }}
**Confidence Level:** {{ confidence_level }}

## Summary

{{ summary }}

## Key Findings

{% for finding in key_findings %}
- {{ finding }}
{% endfor %}

---
*Executive Summary - Deep Research Report Generation Agent System*
"""
        
        template = Template(template_content)
        return template.render(**summary_data)